kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: tomcat-deployment-hpa
  namespace: myserver
spec:
  scaleTargetRef: #定义目标资源
    apiVersion: apps/v1 #目标资源API版本
    kind: Deployment #目标资源类型为Deploymen
    name: tomcat-deployment #目标资源名称
  minReplicas: 2  #最小副本数
  maxReplicas: 10 #最大副本数
  behavior: #定义行为
    scaleDown:  #缩容配置
      stabilizationWindowSeconds: 30 #窗口稳定期，防止在此期间pod数量频繁波动
      policies: #具体策略
        - type: Percent #基于百分比进行pod调整
          value: 100 #允许对当前pod数量的百分之百进行调整
          periodSeconds: 15 #间隔时间为15s，每间隔15s允许对pod副本数量的百分之百调整，直到缩容到minReplicas
    scaleUp: #扩容配置
      stabilizationWindowSeconds: 0 #窗口稳定期，防止在此期间pod数量频繁波动
      policies: #具体策略
        - type: Percent
          value: 100 #允许对当前pod数量的百分之百进行调整
          periodSeconds: 15 #间隔时间为15s，每间隔15s允许对pod副本数量的百分之百调整，直到扩容到maxReplicas
  metrics: #定义指标来源
    - type: Pods #类型为pod指标
      pods: #定义具体pod指标
        metric: #指标配置
          name: network_receive_bytes #指标名称
          #name: tomcat_session_active #指标名称
        target: #目标匹配配置
          type: AverageValue #每秒平均值
          averageValue: 409600m #平均每个pod带宽速率达到50Kb就进行扩容,50(Kb)*1024(bytes)*8(bit)
