# See https://cloud.google.com/cloud-build/docs/build-config                                            
timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90'
    entrypoint: make
    env:
    - TAG=$_PULL_BASE_REF
    args:
    - push-all
